languageCode = "en-us"
baseurl = "http://learntla.com"
title = "Learn TLA"
theme = "hugo-theme-learn"
googleAnalytics = "UA-90708265-1"
pygmentsUseClassic = true
PygmentsCodeFences = true

[Params]
  Author = "Hillel Wayne"
  disableSearch = true
  disableInlineCopyToClipBoard = true
  disableAssetsBusting = true
